version: '3.8'
services:
    api-service:
        build: .
        container_name: prd-telegram-webhook
        volumes:
            - ./app:/code
        ports:
            - 80:5000
        restart: always

